=== MacFJA/php-redisearch-integration/src/Xml/schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="redis-search" type="RediSearchType"/>
    <xs:complexType name="stopsWordsType">
        <xs:sequence>
            <xs:element type="xs:string" name="word" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="idType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" use="required">
                    <xs:simpleType xml:base="xs:string">
                        <xs:restriction>
                            <xs:enumeration value="getter" />
                            <xs:enumeration value="property" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="abstractFieldType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:boolean" name="noindex" use="optional"/>
                <xs:attribute type="xs:string" name="property" use="optional"/>
                <xs:attribute type="xs:string" name="getter" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="textFieldType">
        <xs:simpleContent>
            <xs:extension base="abstractFieldType">
                <xs:attribute type="xs:string" name="nostem" use="optional"/>
                <xs:attribute type="xs:float" name="weight" use="optional"/>
                <xs:attribute type="xs:string" name="phonetic" use="optional"/>
                <xs:attribute type="xs:boolean" name="sortable" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="numericFieldType">
        <xs:simpleContent>
            <xs:extension base="abstractFieldType">
                <xs:attribute type="xs:boolean" name="sortable" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="tagFieldType">
        <xs:simpleContent>
            <xs:extension base="abstractFieldType">
                <xs:attribute type="xs:string" name="separator" use="optional" />
                <xs:attribute type="xs:boolean" name="sortable" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="geoFieldType">
        <xs:simpleContent>
            <xs:extension base="abstractFieldType"/>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="fieldsType">
        <xs:sequence>
            <xs:element type="textFieldType" name="text-field" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="numericFieldType" name="numeric-field" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="tagFieldType" name="tag-field" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="geoFieldType" name="geo-field" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="suggestionType">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:float" name="score" use="optional"/>
        <xs:attribute type="xs:string" name="payload" use="optional"/>
        <xs:attribute type="xs:string" name="group" use="optional"/>
        <xs:attribute type="xs:boolean" name="increment" use="optional"/>
    </xs:complexType>
    <xs:complexType name="suggestionsType">
        <xs:sequence>
            <xs:element type="suggestionType" name="property" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="suggestionType" name="getter" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="classType">
        <xs:sequence>
            <xs:element type="stopsWordsType" name="stops-words" maxOccurs="1" minOccurs="0">
                <xs:unique name="UniqueStopWord">
                    <xs:selector xpath="*"/>
                    <xs:field xpath="."/>
                </xs:unique>
            </xs:element>
            <xs:element type="fieldsType" name="fields" maxOccurs="1" minOccurs="0">
                <xs:unique name="UniqueFieldName">
                    <xs:selector xpath="*"/>
                    <xs:field xpath="."/>
                </xs:unique>
            </xs:element>
            <xs:element type="suggestionsType" name="suggestions" maxOccurs="1" minOccurs="0"/>
            <xs:element type="idType" name="id" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="indexname" use="optional"/>
        <xs:attribute type="xs:string" name="documentprefix" use="optional"/>
    </xs:complexType>
    <xs:complexType name="RediSearchType">
        <xs:sequence>
            <xs:element type="classType" name="class" maxOccurs="unbounded" minOccurs="1" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== MacFJA/php-redisearch-integration/tests/fixtures/xml/example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<redis-search xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://github.com/MacFJA/php-redisearch-integration/blob/main/src/Xml/schema.xsd">
    <class name="MacFJA\RediSearch\Integration\tests\fixtures\xml\Person" indexname="person" documentprefix="document-id-">
        <id type="property">id</id>
        <stops-words>
            <word>the</word>
            <word>redis</word>
        </stops-words>
        <fields>
            <text-field nostem="false" weight="1.0" phonetic="fr" sortable="true" noindex="false">firstname</text-field>
            <numeric-field property="age" sortable="false" noindex="false">age</numeric-field>
            <tag-field getter="getSkills" separator="|" sortable="false" noindex="false">skill</tag-field>
            <geo-field getter="getCoordinate" noindex="false">address</geo-field>
        </fields>
        <suggestions>
            <property name="firstname" type="word" payload="type:firstname" score="0.5" group="nameSuggestion" />
            <getter name="getLastname" type="full" group="nameSuggestion" />
            <getter name="getCity" type="full" />
        </suggestions>
    </class>
</redis-search>

=== MacFJA/php-redisearch-integration/tests/fixtures/City.xml
<?xml version="1.0" encoding="UTF-8" ?>
<redis-search xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../src/Xml/schema.xsd">
    <class name="MacFJA\RediSearch\Integration\tests\fixtures\City" indexname="cities" documentprefix="city-">
        <fields>
            <text-field nostem="false" weight="2.0" sortable="true" noindex="false">name</text-field>
            <text-field nostem="false" weight="0.8" sortable="true" noindex="false">country</text-field>
            <numeric-field sortable="true" noindex="false">population</numeric-field>
            <tag-field getter="getAllLanguages" separator="|" sortable="false" noindex="false">languages</tag-field>
            <geo-field getter="getGpsCoordinate" noindex="false">coordinate</geo-field>
        </fields>
        <suggestions>
            <property name="name" score="1.5" group="place" />
            <getter name="getCountry" group="place" payload="country" />
        </suggestions>
    </class>
</redis-search>
